### ISSUE TITLE
Missing "browser_specific_settings" for Firefox.

### ISSUE THREAD

**Issue by rakino** [Sevichecc/miniflux-injector#1]
I can't load the released zip file to Firefox.  Comparing to the one currently on addons.mozilla.org it seems "browser_specific_settings" is missing from manifest.json:

```diff
diff --git a/gnu/store/yk0jms3vigzg49qvrc4pkn584s6w8gh3-miniflux-injector-2.3.2/{528ec801-2e29-4cb9-ae71-5a90503138d1}/manifest.json b/gnu/store/kz7w2ihknf83g8kf2sc6h6x0dfrqwd6k-miniflux-injector-2.3.2/{528ec801-2e29-4cb9-ae71-5a90503138d1}/manifest.json
index 668a86b..bcddfc8 100644
--- a/gnu/store/yk0jms3vigzg49qvrc4pkn584s6w8gh3-miniflux-injector-2.3.2/{528ec801-2e29-4cb9-ae71-5a90503138d1}/manifest.json
+++ b/gnu/store/kz7w2ihknf83g8kf2sc6h6x0dfrqwd6k-miniflux-injector-2.3.2/{528ec801-2e29-4cb9-ae71-5a90503138d1}/manifest.json
@@ -266,5 +266,10 @@
     "https://*/*",
     "http://*/*",
     "storage"
-  ]
+  ],
+  "browser_specific_settings": {
+    "gecko": {
+      "id": "{528ec801-2e29-4cb9-ae71-5a90503138d1}"
+    }
+  }
 }
\ No newline at end of file
```

BTW can you release 2.3.3 to addons.mozilla.org? :)

**Comment by sevi418** [comment]
Hi @rakino, 

According to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings), the `browser_specific_settings` section is not mandatory for local development, as Firefox automatically handles this during the signing process when publishing to addons.mozilla.org.
For development purposes, you can load the unsigned extension in Firefox using these steps:

1. Open Firefox
2. Navigate to `about:debugging`
3. Click "This Firefox"
4. Click "Load Temporary Add-on"
5. Select the release package file

And I've just submitted version 2.3.3 to addons.mozilla.org. It should be available soon! Thank you! 😊

**Comment by rakino** [comment]
Thanks!
